//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnibraCred.Pontuacao.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class DebitoPontos
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public int fatura_id { get; set; }
        [DataMember]
        public int cartao_id { get; set; }
        [DataMember]
        public int pontosQtd { get; set; }
        [DataMember]
        public System.DateTime dtUtilizacao { get; set; }
    }
}
