//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnibraCred.Pontuacao.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontuacaoSet
    {
        public int Id { get; set; }
        public int tipo { get; set; }
        public System.DateTime Validade { get; set; }
        public int FaturaId { get; set; }
        public double PontosQtd { get; set; }
        public int TaxaConversaoId { get; set; }
    
        public virtual TaxaConversaoSet TaxaConversaoSet { get; set; }
    }
}
