//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnibraCred.Pontuacao.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontuacaoFatura
    {
        public int id { get; set; }
        public int taxaConversao_id { get; set; }
        public int fatura_id { get; set; }
        public int pontosQtd { get; set; }
        public int cartao_id { get; set; }
        public System.DateTime dtInclusao { get; set; }
        public System.DateTime dtVigencia { get; set; }
    
        public virtual TaxaConversao TaxaConversao { get; set; }
    }
}
