//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnibraCred.Pontuacao.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxaConversaoSet
    {
        public TaxaConversaoSet()
        {
            this.PontuacaoSet = new HashSet<PontuacaoSet>();
        }
    
        public int Id { get; set; }
        public decimal TaxaValor { get; set; }
        public System.DateTime DataInicioVigencia { get; set; }
        public System.DateTime DataInclusao { get; set; }
    
        public virtual ICollection<PontuacaoSet> PontuacaoSet { get; set; }
    }
}
