//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnibraCred.Pontuacao.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class TaxaConversao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxaConversao()
        {
            this.PontuacaoFatura = new HashSet<PontuacaoFatura>();
        }

        [DataMember]
        public int id { get; set; }
        [DataMember]
        public decimal taxaValor { get; set; }
        [DataMember]
        public System.DateTime dtInclusao { get; set; }
        [DataMember]
        public System.DateTime dtVigencia { get; set; }
        [DataMember]
        public int diasValidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PontuacaoFatura> PontuacaoFatura { get; set; }
    }
}
